map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}
server {
	port 2199;
	listen 127.0.0.1:2199 ssl reuseport;
	listen [::2]:2199 ssl reuseport;
	listen [::1]:2199 ssl reuseport;
	server_name _;
	# ssl configuration
	include nginx_ssl_certificate.conf;
	ssl_dhparam         dhparams.pem;
	ssl_session_cache   shared:SSL:1m;
	ssl_session_timeout 5m;
	include nginx_ssl_protocol.conf;
	include nginx_ssl_ciphersuite.conf;
	location = /websocket/video {
		proxy_pass http://127.0.0.1:42199;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		proxy_set_header Host $host;
		proxy_set_header X-real-ip $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}
	location = / {
		add_header Content-Type 'text/html';
		add_header X-Content-Type-Options "nosniff" always;
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
		add_header Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self'; object-src 'self'; style-src 'self'" always;
		return 200 '<!DOCTYPE html>
                                                                                                  
    <html lang=\"en\">
                                                                                        
    <head>
                                                                                                        
    <title>Certificate detection page</title>
                                                                     
    <META http-equiv=\"X-UA-Compatible\" content=\"IE=10\">
                                               
    <meta charset=utf-8 http-equiv=\"Content-Language\" content=\"en\"/>
                                  
    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>
                              
    <script type=\"text/javascript\">
                                                                         
        window.onload = function() {window.addEventListener(\"message\",Receiver);}
                           
        function Receiver(event) {event.source.postMessage(\"Certificate OK.\", event.origin);                  
    window.open(\'\',\'_self\', \'\');window.close();}
                                                
        function CloseWindow(){window.open(\'\', \'_self\', \'\');window.close();}
                    
    </script>
                                                                                                     
    </head>
                                                                                                       
    <body>
                                                                                                        
    <table>
                                                                                                       
        <tr><td>Your SSL certificate has been accepted by the browser. You could close this window                  
    now.</td></tr>
                                                                                                
        <tr><td align=\"middle\"><input id=\"btn_close\" type=\"button\" onclick=\"CloseWindow()\"  
    value=\"Close\" /></td></tr>
                                                                              
    </table>
                                                                                                      
    </body>
                                                                                                       
    </html>';
	}
}