#server {
#	port 50080;
#	include nginx_ssl_certificate.conf;
#	location ~* /redfish/v1/SessionService/Sessions {
#		proxy_set_header X-Server-IP $server_addr;
#		proxy_set_header X-Server-Port $server_port;
#		proxy_set_header X-Real-IP $remote_addr;
#		proxy_set_header X-Real-Port $remote_port;
#		proxy_set_header X-SSL_Client_serial $ssl_client_serial;
#		proxy_set_header X-SSL-Client-subject $ssl_client_s_dn;
#		proxy_set_header X-SSL-Client-issuer $ssl_client_i_dn;
#		proxy_http_version 1.1;
#		if ($request_method = POST) {
#			proxy_pass http://redfish_proxy;
#		}
#		if ($request_method != POST) {
#			return 405;
#		}
#	}
#	location / {
#		return 404;
#	}
#	include nginx_ssl_protocol.conf;
#	include nginx_ssl_ciphersuite.conf;
#	ssl_verify_client off;
#}
