ssl_dhparam         dhparams.pem;
ssl_session_cache   shared:SSL:1m;
ssl_session_timeout 5m;

include nginx_ssl_protocol.conf;
include nginx_ssl_ciphersuite.conf;
include nginx_ssl_verify_client.conf;