server {
	port 443;
	port 40443;
	listen 127.0.0.1:443 ssl reuseport;
	listen 127.0.0.1:40443 ssl reuseport;
	listen [::2]:443 ssl reuseport;
	listen [::2]:40443 ssl reuseport;
	listen [fe80::9e7d:a3ff:fe28:6ffa%veth]:40443 ssl reuseport;
	listen [fe80::9e7d:a3ff:fe28:6ffa%veth]:443 ssl reuseport;
	server_name _;
	
	include nginx_ssl_certificate.conf;
	include nginx_https_server_ext.conf;
}
